from __future__ import annotations

import socket

NODE_ID: str = socket.gethostname()

DEFAULT_MQTT_PORT: int = 1883
DEFAULT_MQTT_TLS_PORT: int = 8883
DEFAULT_MQTT_WS_PORT: int = 9001
DEFAULT_GRPC_PORT: int = 50051
DEFAULT_HTTP_PORT: int = 8080
DEFAULT_PROMETHEUS_PORT: int = 9090

HEARTBEAT_INTERVAL: float = 5.0
HEARTBEAT_TIMEOUT: float = 15.0
RECONNECT_BACKOFF_MIN: float = 1.0
RECONNECT_BACKOFF_MAX: float = 60.0
RECONNECT_BACKOFF_FACTOR: float = 2.0

CRDT_SYNC_INTERVAL: float = 2.0
CRDT_FULL_SYNC_INTERVAL: float = 60.0
CRDT_DELTA_SYNC_INTERVAL: float = 1.0
CRDT_TOMBSTONE_CLEANUP_INTERVAL: float = 300.0
CRDT_MAX_TOMBSTONE_AGE: float = 3600.0

GOSSIP_INTERVAL: float = 10.0
GOSSIP_FANOUT: int = 3
GOSSIP_MAX_PEERS: int = 20

LEADER_ELECTION_TIMEOUT_MIN: float = 2.0
LEADER_ELECTION_TIMEOUT_MAX: float = 5.0
LEADER_HEARTBEAT_INTERVAL: float = 1.0

TASK_ALLOCATION_INTERVAL: float = 5.0
TASK_DEADLINE_BUFFER: float = 30.0

FORMATION_UPDATE_INTERVAL: float = 0.5
PATH_PLANNING_INTERVAL: float = 2.0
COLLISION_AVOIDANCE_RADIUS: float = 2.0

SENSOR_READ_INTERVAL: float = 0.1
SENSOR_FUSION_INTERVAL: float = 0.5
TELEMETRY_PUBLISH_INTERVAL: float = 1.0

VECTOR_DB_INDEX_INTERVAL: float = 60.0
VECTOR_DB_SEARCH_TOP_K: int = 10

MODEL_HEARTBEAT_INTERVAL: float = 30.0
MODEL_CACHE_SIZE: int = 5
MODEL_INFERENCE_TIMEOUT: float = 30.0

RATE_LIMIT_DEFAULT: int = 60
RATE_LIMIT_WINDOW: int = 60

MAX_MESSAGE_SIZE: int = 4 * 1024 * 1024
MAX_QUEUE_SIZE: int = 10000
MAX_PEERS: int = 100

STALE_ROVER_TIMEOUT: float = 30.0
MISSION_TIMEOUT: float = 3600.0

ENCODING: str = "utf-8"
MSG_PACK_ENCODING: int = 5
